### PR TITLE
Formatting and grammar correction of german translation

### PR DESCRIPTION
**Pull request by JohannesKnopp**
Corrected asch_cli_usage_de.md, asch_dapps_intruduction_de.md & first 1000 lines asch_http_interface_de.md

### CODE REVIEW

**Comment by yanyiwu** [comment]
@a1300 can you help review this pr please. if it helps,

**Comment by yanyiwu** [comment]
Can you post your asch wallet adress, we will send you some xas reward for your contribution. Thank you agagin

**Comment by JohannesKnopp** [comment]
Address: AEwAdpCenPB5ZtcewSjxKqQs2MaswbYPie
Thank you very much

**Comment by yanyiwu** [comment]
ok

**Pull request merged**
